const quotes = [
    "Con đường duy nhất để đi đến tương lai là tự mình tạo ra nó.",
    "Cuộc sống là 10% những gì xảy ra và 90% cách chúng ta đối diện với nó.",
    "Thời gian là hữu hạn, đừng lãng phí nó để sống cuộc đời của người khác.",
    "Thành công thường đến với những người quá bận rộn để đi tìm nó.",
    "Đừng ngại từ bỏ những điều tốt để theo đuổi điều tuyệt vời.",
    "Tôi nhận ra rằng, càng chăm chỉ làm việc, tôi càng may mắn.",
    "Cách duy nhất để làm nên điều vĩ đại là yêu thích công việc mình làm.",
    "Hãy sống như thể mỗi ngày là ngày cuối cùng của cuộc đời bạn.",
    "Không có gì là không thể, chỉ cần bạn thực sự muốn và quyết tâm làm.",
    "Hạnh phúc không phải là đích đến mà là hành trình bạn đang đi.",
    "Người thành công không phải là người chưa bao giờ thất bại mà là người không bao giờ bỏ cuộc.",
    "Điều quan trọng không phải bạn đang đi nhanh đến đâu, mà là bạn có đang đi đúng hướng.",
    "Sự thay đổi bắt đầu từ chính bản thân bạn.",
    "Mỗi khi bạn ngã, hãy đứng dậy mạnh mẽ hơn.",
    "Cuộc sống không phải là chờ đợi cơn bão qua đi mà là học cách khiêu vũ dưới mưa.",
    "Những gì bạn nghĩ hôm nay sẽ quyết định tương lai của bạn ngày mai.",
    "Bạn sẽ không bao giờ đi hết con đường nếu bạn không bắt đầu bước đi.",
    "Không bao giờ là quá muộn để bắt đầu lại từ đầu.",
    "Dũng cảm không phải là không sợ hãi, mà là vượt qua nỗi sợ để tiến bước.",
    "Hãy tin vào chính mình, vì chính bạn là người duy nhất biết bạn có thể làm gì.",
    "Không có khó khăn nào là mãi mãi, chỉ có ý chí vững vàng là trường tồn.",
    "Người khôn ngoan là người học hỏi từ thất bại nhiều hơn từ thành công.",
    "Cơ hội không đến hai lần, vì vậy hãy nắm lấy khi nó xuất hiện.",
    "Thất bại chỉ là một bước nhỏ trên hành trình đến thành công.",
    "Sức mạnh lớn nhất của con người chính là sự kiên nhẫn và lòng quyết tâm.",
    "Đôi khi bạn phải tự tạo động lực cho chính mình, đừng chờ đợi người khác làm điều đó.",
    "Không phải ai sinh ra cũng vĩ đại, mà vĩ đại là kết quả của sự nỗ lực không ngừng.",
    "Mỗi ngày là một cơ hội để trở thành phiên bản tốt hơn của chính mình.",
    "Tương lai thuộc về những ai tin vào vẻ đẹp của ước mơ của mình.",
    "Khi bạn muốn từ bỏ, hãy nghĩ đến lý do vì sao bạn bắt đầu.",
    "Một suy nghĩ tích cực vào buổi sáng có thể thay đổi cả ngày của bạn.",
    "Nếu bạn không thay đổi hướng đi, bạn sẽ kết thúc nơi mà bạn đang hướng tới.",
    "Cách nhanh nhất để đạt được một giấc mơ là bắt đầu ngay bây giờ.",
    "Hãy tập trung vào những gì bạn có thể kiểm soát và để mọi thứ khác trôi qua.",
    "Hành trình dài ngàn dặm bắt đầu từ một bước chân nhỏ.",
    "Thành công không đến từ những gì bạn làm thỉnh thoảng, mà từ những gì bạn làm đều đặn.",
    "Mỗi ngày là một cơ hội mới để tạo ra sự khác biệt.",
    "Bạn không thể thay đổi quá khứ, nhưng bạn có thể tạo nên tương lai.",
    "Hãy luôn mỉm cười, bởi đó là cách dễ nhất để truyền cảm hứng cho người khác.",
    "Thành công không phải là đích đến, mà là cách bạn vượt qua hành trình.",
    "Đừng bao giờ để nỗi sợ thất bại ngăn bạn thử điều gì đó mới mẻ.",
    "Bầu trời chỉ đẹp khi có những áng mây, cũng như cuộc sống chỉ thú vị khi có thử thách.",
    "Bạn mạnh mẽ hơn bạn nghĩ, thông minh hơn bạn tin, và can đảm hơn bạn cảm nhận.",
    "Chỉ cần bạn không ngừng tiến lên, không điều gì có thể ngăn cản bạn.",
    "Hãy làm hôm nay tuyệt vời, bởi đó là tất cả những gì chúng ta thực sự có.",
    "Mỗi sai lầm là một bài học quý giá, hãy cảm ơn nó vì đã làm bạn trưởng thành hơn.",
    "Đừng chờ đợi cơ hội, hãy tạo ra nó.",
    "Hãy yêu chính mình trước khi yêu bất kỳ ai khác.",
    "Khó khăn chỉ là một phần trong quá trình, đừng để nó ngăn bạn tiến tới thành công.",
    "Tương lai tốt đẹp bắt đầu từ quyết định bạn đưa ra hôm nay.",
    "Hãy sống trọn vẹn từng khoảnh khắc và luôn biết ơn.",
    "Chúng ta có thể không kiểm soát được mọi thứ, nhưng chúng ta kiểm soát được cách chúng ta phản ứng.",
    "Khi bạn cảm thấy muốn từ bỏ, hãy nhớ lý do bạn bắt đầu.",
    "Không có điều gì là thất bại hoàn toàn nếu bạn học được điều gì đó từ nó.",
    "Hãy tỏa sáng theo cách của riêng bạn, không cần phải so sánh với bất kỳ ai.",
    "Hãy hành động ngay cả khi bạn chưa hoàn toàn sẵn sàng, vì sự hoàn hảo là một hành trình chứ không phải đích đến.",
    "Sự khác biệt giữa người mơ mộng và người thành công là hành động.",
    "Người chiến thắng là người không ngừng cố gắng, ngay cả khi không ai tin tưởng họ.",
    "Thế giới sẽ tốt đẹp hơn khi bạn quyết định góp phần làm điều gì đó tốt đẹp.",
    "Hãy nhớ rằng ngay cả ngày tồi tệ nhất cũng chỉ kéo dài 24 giờ.",
    "Hạnh phúc không phải là có mọi thứ, mà là biết trân trọng những gì bạn có.",
    "Đừng bao giờ ngại thử thách, bởi vì chính thử thách làm bạn mạnh mẽ hơn.",
    "Những việc nhỏ bạn làm hôm nay sẽ tạo nên thành công lớn ngày mai."
];


const quoteText = document.getElementById('quote-text');
const generateBtn = document.getElementById('generate-btn');

function generateQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteText.textContent = quotes[randomIndex];
}

generateBtn.addEventListener('click', generateQuote);
